apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tanzu-pro
  namespace: cert-manager
spec:
  secretName: wildcard-tanzu-pro-tls
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
  dnsNames:
  - "*.tanzu.pro"
  - "*.tap-i1.tanzu.pro"
  - "*.internal.tanzu.pro"